stages:
  - docker
  - test

variables:
  BUILD_IMAGE: "$CI_REGISTRY_IMAGE:ci-master-2019-12-11"
  GIT_CLEAN_FLAGS: "-ffdxq"

build-image:
  stage: docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - if docker pull "$BUILD_IMAGE"; then echo "Image already exists!"; exit 1; fi
    - docker build --force-rm -t "$BUILD_IMAGE" - < misc/Dockerfile.build
    - docker push "$BUILD_IMAGE"
    - docker rmi "$BUILD_IMAGE"
  only:
    variables:
      - $NEW_BUILD_IMAGE
  tags:
    - shell

.docker_template: &docker_definition
  image: "$BUILD_IMAGE"
  tags:
    - docker

ce-bench:
  stage: test
  variables:
    COMPILER: bench
  script:
    - misc/ci-local.sh ce-bench
  <<: *docker_definition
